import { formatCurrency } from '../../pos-utils'
import type { Product } from '../../types'
import { StatCard } from '../StatCard'

type Summary = { grossSales: number; cashSales: number; cardSales: number; eWalletSales: number; expensesTotal: number; allowancesTotal: number; commissionTotal: number; ldCommissionTotal: number; netSales: number; transactions: number }
type Props = { summary: Summary; trend: { label: string; value: number }[]; registerLocked: boolean; cashier: string; shiftDate: string; register: string; lowStock: Product[]; audit: Array<{ id: string; action: string; description: string }> }
export function DashboardPage({ summary, trend, registerLocked, cashier, shiftDate, register, lowStock, audit }: Props) {
  const maximum = Math.max(...trend.map((entry) => entry.value), 1)
  return <div className="page-grid"><div className="stats-grid"><StatCard label="Today's Sales" value={formatCurrency(summary.grossSales)} subtext={`${summary.transactions} transactions`} /><StatCard label="Cash Sales" value={formatCurrency(summary.cashSales)} subtext="Cash collected" /><StatCard label="Card Sales" value={formatCurrency(summary.cardSales)} subtext="Card payments" /><StatCard label="E-Wallet Sales" value={formatCurrency(summary.eWalletSales)} subtext="Digital payments" /><StatCard label="Expenses" value={formatCurrency(summary.expensesTotal)} subtext="Operating costs" /><StatCard label="Allowances" value={formatCurrency(summary.allowancesTotal)} subtext="Staff support" /><StatCard label="Commissions" value={formatCurrency(summary.commissionTotal)} subtext="Sales commission" /><StatCard label="LD Commission" value={formatCurrency(summary.ldCommissionTotal)} subtext="Lead payouts" /><StatCard label="Net Sales" value={formatCurrency(summary.netSales)} subtext="After discounts" accent /></div><div className="dashboard-panels"><div className="panel"><div className="panel-header"><h3>Sales Trend</h3></div><div className="sales-chart">{trend.map((entry) => <div key={entry.label} className="chart-bar-group"><div className="chart-bar" style={{ height: `${Math.max((entry.value / maximum) * 100, entry.value > 0 ? 8 : 2)}%` }} /><span>{entry.label}</span></div>)}</div></div><div className="panel"><div className="panel-header"><h3>Register Status</h3></div><div className="status-box"><p className={`status-badge ${registerLocked ? 'locked' : 'open'}`}>{registerLocked ? 'REGISTER LOCKED' : 'REGISTER OPEN'}</p><ul><li>Current cashier: {cashier || '—'}</li><li>Current shift: {shiftDate || 'No active shift'}</li><li>Register: {register || '—'}</li></ul></div></div><div className="panel"><div className="panel-header"><h3>Low Stock Alerts</h3></div><div className="status-box">{lowStock.length === 0 ? <p>All active products are stocked adequately.</p> : <ul>{lowStock.map((product) => <li key={product.id}>{product.name} — {product.stock} left</li>)}</ul>}</div></div><div className="panel"><div className="panel-header"><h3>Recent Activity</h3></div><div className="status-box"><ul>{audit.map((entry) => <li key={entry.id}><strong>{entry.action}</strong> — {entry.description}</li>)}</ul></div></div></div></div>
}
